project:
  type: website
  output-dir: ./docs

website:
  title: "khuongduying"
  navbar:
    background: primary
    logo:  GO_WITH_THE_FLOW/2.png
    search: true
    left:
      - text: "Home"
        file: index.qmd
      # - text: "Best Practice"
      #   menu:
      #     - text: "Git"
      #       href: best_practice/git/*
      #     - text: "Test"
      #       href: best_practice/test/*
      - sidebar:best_practice
      - sidebar:machine_learning
      - sidebar:fundamentals
      - sidebar:reference
      - sidebar:basic
      - sidebar:advance
      - about.qmd
      - news.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/khuongduying/
      - icon: github
        menu:
          - text: My repositories
            url: https://github.com/khuongduying
          - text: Report a bug
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    background: light
    left: "Copyright 2024, Duy Dao" 
    right: 
      - icon: github
        href: https://github.com/khuongduying
      - icon: linkedin 
        href: https://www.linkedin.com/in/khuongduying/
  reader-mode: true
  repo-url: https://github.com/khuongduying
  repo-actions: [edit, issue]

  sidebar:
    - id: best_practice
      title: "Best Practice"
      style: "docked"
      search: true
      background: light
      collapse-level: 2
      contents:
        - section: Git
          contents:
            - auto: best_practice/git/*
        - section: Useful Bash
          contents:
            - auto: best_practice/useful_bash/*
        - section: test
          contents:
            - news.qmd
    
    - id: machine_learning
      title: "Machine Learning"
      contents:
        - auto: machine_learning/*
        # navigation items
    
    - id: fundamentals
      title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items
    
    - id: reference
      title: "Reference"
      contents:
        - reference.qmd
        # navigation items

    - id: basic
      title: "Basic"
      contents:
        - auto: Basic/
    - id: advance
      title: "Advance"
      contents:
        - auto: Advance/*
format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true
    code-link: true
    code-fold: false
    code-overflow: wrap
    code-tools:
      source: true
      toggle: false
      caption: none
    code-block-bg: true
    code-block-border-left: "#31BAE9"
python:
  jupyter: python3
  freeze-requirements: false
editor: visual
highlight-style: pygments